"""init database

Revision ID: 4f338214081d
Revises: 
Create Date: 2018-05-04 21:18:04.376422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f338214081d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('company',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyname', sa.String(length=32), nullable=False),
    sa.Column('logo_url', sa.String(length=256), nullable=True),
    sa.Column('com_website', sa.String(length=256), nullable=True),
    sa.Column('com_shortinfo', sa.String(length=256), nullable=True),
    sa.Column('com_description', sa.String(length=512), nullable=True),
    sa.Column('com_address', sa.String(length=32), nullable=True),
    sa.Column('comrecruit_num', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_companyname'), 'company', ['companyname'], unique=True)
    op.create_table('job',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobname', sa.String(length=32), nullable=False),
    sa.Column('salary_up', sa.Integer(), nullable=True),
    sa.Column('salary_down', sa.Integer(), nullable=True),
    sa.Column('exper_need', sa.String(length=32), nullable=True),
    sa.Column('work_address', sa.String(length=32), nullable=True),
    sa.Column('job_need', sa.String(length=128), nullable=True),
    sa.Column('job_description', sa.String(length=256), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_jobname'), 'job', ['jobname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_jobname'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_company_companyname'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
